[package]
name = "is-fast"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = { version = "0.11.14", features = ["blocking", "cookies"] }
scraper = "0.14.0"
thiserror = "2.0.11"
once_cell = "1.20.3"
syntect = "5.2.0"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
dirs = "6.0.0"
