[package]
name = "is-fast"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = { version = "0.12.12", features = ["blocking", "cookies"] }
scraper = "0.23.1"
thiserror = "2.0.11"
once_cell = "1.20.3"
syntect = "5.2.0"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
dirs = "6.0.0"
clap = { version = "4.5.31", features = ["derive"] }
open = "5.3.2"
dashmap = "7.0.0-rc1"
globset = "0.4.16"
rusqlite = {version = "0.33.0", features = ["bundled"]}

[build-dependencies]
clap = { version = "4.5.31", features = ["derive", "cargo", "env"] }
clap_mangen = "0.2.26"
