[package]
name = "is-fast"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
html2text = "0.14.0"
ncurses = "5.101.0"
ratatui = "0.29.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
scraper = "0.14.0"
tempfile = "3.17.1"
