[package]
name = "is-fast"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-tui = "7.0.0"
crossterm = "0.28.1"
html2text = "0.14.0"
ncurses = "5.101.0"
ratatui = "0.29.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
scraper = "0.14.0"
tempfile = "3.17.1"
thiserror = "2.0.11"
regex = "1.11.1"
strip-ansi-escapes = "0.2.1"
once_cell = "1.20.3"
