[headers]
"User-Agent" = "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0"
"Accept" = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
"Accept-Language" = "en-US,en;q=0.5"
"Accept-Encoding" = "gzip, deflate, br, zstd"
"Referer" = "https://www.google.com/"
"Connection" = "keep-alive"
"Upgrade-Insecure-Requests" = "1"
"Sec-Fetch-Dest" = "document"
"Sec-Fetch-Mode" = "navigate"
"Sec-Fetch-Site" = "cross-site"
"Sec-Fetch-User" = "?1"
"Priority" = "u=0, i"
"TE" = "trailers"