name: Run nix build 

on:
  push:
    paths:
      - 'src/*'
      - 'flake.*'
      - 'Cargo.*'
  pull_request:
    paths:
      - 'src/*'
      - 'flake.*'
      - 'Cargo.*'

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v21

      - name: Nix build
        run: nix build
